# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nistagram-auth'
    static_configs:
      - targets: ['nistagram-auth:9091']

  - job_name: 'nistagram-posts'
    static_configs:
      - targets: ['nistagram-posts:8085']

  - job_name: 'nistagram-users'
    static_configs:
      - targets: ['nistagram-users:8084']

  - job_name: 'nistagram-media'
    static_configs:
      - targets: ['nistagram-media:8089']

  - job_name: 'nistagram-administration'
    static_configs:
      - targets: ['nistagram-administration:8088']

  # - job_name: 'grafana'
  #   static_configs:
  #     - targets: ['grafana:4000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']